

services:
  backend:
    container_name: airfare-backend
    hostname: airfare-backend
    build:
      context: ./airfare_backend
      target: development
    ports:
      - "5000:5000"
    depends_on:
      - frontend  # optional if you need backend to wait for frontend
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    restart: unless-stopped

  frontend:
    container_name: airfare-frontend
    build:
      context: ./airfare_frontend
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_API=http://51.20.77.166:5000
    depends_on:
      - backend
    command: npm run dev
    restart: unless-stopped

